In [5]:
import numpy as np
T = np.matrix([[0.2,0.3,0.1],[0.5,0.6,0.4],[0.3,0.1,0.5]])

In [3]:
import numpy as np 
T = np.matrix([[0.2,0.3,0.1],[0.5,0.6,0.4],[0.3,0.1,0.5]])
S = np.linalg.matrix_power(T, 100)
print(S)

[[ 0.22857143  0.22857143  0.22857143]
 [ 0.52857143  0.52857143  0.52857143]
 [ 0.24285714  0.24285714  0.24285714]]


In [4]:
import numpy as np
A = np.matrix([[.5,0,0],[.5,.6,0],[0,.4,1]])
B = np.linalg.matrix_power(A,100)
print(B)

[[  7.88860905e-31   0.00000000e+00   0.00000000e+00]
 [  3.26659308e-22   6.53318624e-23   0.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00]]


In [2]:
import numpy as np
A = np.matrix([[.5,.25],[.5, .75]])
B = np.linalg.matrix_power(A,100000)
print(B)

[[ 0.33333333  0.33333333]
 [ 0.66666667  0.66666667]]
