In [ ]:
import numpy as np
#first order matrix creation hehe

#Given that Behavior_1 is the first behavior
A = np.matrix([[]])

#Given that Behavior_2 is the second behavior 
B = np.matrix([[]])

#Given that Behavior_3 is the third behavior
C = np.matrix([[]])

#We need an initial probability distribution, which we will compare to the
#distrbution of the control, where there is no human interaction between the 
#squirrel monkeys while this whole ecotourism thing is happenin' 

Initial = np.matrix([[]])

generateFirstOrderSeq = function(lengthSeq,
                                alphabet,
                                initialProb,
                                firstOrderMatrix)

In [11]:
import numpy as np
import pandas as pd
import networkx as nx
%matplotlib inline
import matplotlib.pyplot as plt
states = ['sleeping', 'eating', 'pooping']
statesprob = [0.35,0.35,0.3]
state_space = pd.Series(statesprob, index=states, name='states')
print(state_space)
print(state_space.sum())

sleeping    0.35
eating      0.35
pooping     0.30
Name: states, dtype: float64
1.0


In [13]:
#create transition matrix
#equals transition probability matrix of changing states given a state
#matrix is size (MxM) where M is number of states
q_df = pd.DataFrame(columns=states, index=states)
q_df.loc[states[0]] = [0.4,0.2,0.4]
q_df.loc[states[1]] = [0.45, 0.45, 0.1]
q_df.loc[states[2]] = [0.45, 0.25, .3]

print(q_df)

q = q_df.values
print('\n', q, q.shape, '\n')
print(q_df.sum(axis=1))

         sleeping eating pooping
sleeping      0.4    0.2     0.4
eating       0.45   0.45     0.1
pooping      0.45   0.25     0.3

 [[0.4 0.2 0.4]
 [0.45 0.45 0.1]
 [0.45 0.25 0.3]] (3, 3) 

sleeping    1.0
eating      1.0
pooping     1.0
dtype: float64


In [14]:
from pprint import pprint 

# create a function that maps transition probability dataframe 
# to markov edges and weights

def _get_markov_edges(Q):
    edges = {}
    for col in Q.columns:
        for idx in Q.index:
            edges[(idx,col)] = Q.loc[idx,col]
    return edges

edges_wts = _get_markov_edges(q_df)
pprint(edges_wts)

{('eating', 'eating'): 0.45,
 ('eating', 'pooping'): 0.1,
 ('eating', 'sleeping'): 0.45,
 ('pooping', 'eating'): 0.25,
 ('pooping', 'pooping'): 0.3,
 ('pooping', 'sleeping'): 0.45,
 ('sleeping', 'eating'): 0.2,
 ('sleeping', 'pooping'): 0.4,
 ('sleeping', 'sleeping'): 0.4}


In [16]:
# create graph object
G = nx.MultiDiGraph()

# nodes correspond to states
G.add_nodes_from(states)
print(f'Nodes:\n{G.nodes()}\n')

# edges represent transition probabilities
for k, v in edges_wts.items():
    tmp_origin, tmp_destination = k[0], k[1]
    G.add_edge(tmp_origin, tmp_destination, weight=v, label=v)
print(f'Edges:')
pprint(G.edges(data=True))    

pos = nx.drawing.nx_pydot.graphviz_layout(G, prog='dot')
nx.draw_networkx(G, pos)

# create edge labels for jupyter plot but is not necessary
edge_labels = {(n1,n2):d['label'] for n1,n2,d in G.edges(data=True)}
nx.draw_networkx_edge_labels(G , pos, edge_labels=edge_labels)
nx.drawing.nx_pydot.write_dot(G, 'pet_dog_markov.dot')

Nodes:
['sleeping', 'eating', 'pooping']

Edges:
[('sleeping', 'sleeping', {'label': 0.4, 'weight': 0.4}),
 ('sleeping', 'eating', {'label': 0.2, 'weight': 0.2}),
 ('sleeping', 'pooping', {'label': 0.4, 'weight': 0.4}),
 ('eating', 'sleeping', {'label': 0.45, 'weight': 0.45}),
 ('eating', 'eating', {'label': 0.45, 'weight': 0.45}),
 ('eating', 'pooping', {'label': 0.1, 'weight': 0.1}),
 ('pooping', 'sleeping', {'label': 0.45, 'weight': 0.45}),
 ('pooping', 'eating', {'label': 0.25, 'weight': 0.25}),
 ('pooping', 'pooping', {'label': 0.3, 'weight': 0.3})]


ModuleNotFoundError: No module named 'pydotplus'