In [48]:
#Done -- control matrix
import numpy as np
B = np.matrix([[0,0.26,0.20,0,0.25],[0.09,0.52,0,0,0],[0,0,0.66,0,0],[0,0,0.05,1,0],[0,0,0,0,0]])
print(B)

[[ 0.    0.26  0.2   0.    0.25]
 [ 0.09  0.52  0.    0.    0.  ]
 [ 0.    0.    0.66  0.    0.  ]
 [ 0.    0.    0.05  1.    0.  ]
 [ 0.    0.    0.    0.    0.  ]]


In [52]:
from sklearn.preprocessing import normalize
Column_Normalized = normalize(B, norm='l1', axis=0)
print(Column_Normalized)

[[ 0.          0.33333333  0.21978022  0.          1.        ]
 [ 1.          0.66666667  0.          0.          0.        ]
 [ 0.          0.          0.72527473  0.          0.        ]
 [ 0.          0.          0.05494505  1.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]


In [50]:
#Finding the invariant distribution of the control matrix.
import numpy as np
InvariantDis = np.linalg.matrix_power(B,10000)
print(InvariantDis)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.14705882  1.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]


In [53]:
import numpy as np
T = np.matrix([[1,0.59,0.48,0,0.39],[0,0.27,0,0,0],[0,0,0,0,0],[0,0,0,1,0.29],[0,0,0,0,0.14]])
print(T)

[[ 1.    0.59  0.48  0.    0.39]
 [ 0.    0.27  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.29]
 [ 0.    0.    0.    0.    0.14]]


In [57]:
#Normalizing the experimental matrix
from sklearn.preprocessing import normalize
Column_Normalized = normalize(T, norm='l1', axis=0)
print(Column_Normalized)
S = np.matrix([[1,0.69,1,0,0.48],[0,0.31,0,0,0],[0,0,0,0,0],[0,0,0,1,0.35],[0,0,0,0,0.17]])
print(S)

[[ 1.          0.68604651  1.          0.          0.47560976]
 [ 0.          0.31395349  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.35365854]
 [ 0.          0.          0.          0.          0.17073171]]
[[ 1.    0.69  1.    0.    0.48]
 [ 0.    0.31  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.35]
 [ 0.    0.    0.    0.    0.17]]


In [58]:
#Finding the invariant distribution of the experimental matrix
import numpy as np
InvariantDis2 = np.linalg.matrix_power(S,10000)
print(InvariantDis2)

[[ 1.          1.          1.          0.          0.57831325]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.42168675]
 [ 0.          0.          0.          0.          0.        ]]
